/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ["class"],
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        obsidian: {
          950: '#ffffff',
          900: '#f8fafc',
          850: '#f1f5f9',
          800: '#e2e8f0',
        },
        brand: {
          dark: '#ffffff',
          card: '#ffffff',
          surface: '#f8fafc',
          elevated: '#ffffff',
          cyan: '#0284c7',
          indigo: '#4f46e5',
          violet: '#7c3aed',
          purple: '#9333ea',
          neon: '#0284c7',
        },
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        admin: {
          bg: "#f8fafc",
          card: "#ffffff",
          sidebar: "#ffffff",
          border: "#e2e8f0",
        },
        'surface-tint': '#4f46e5',
        'primary-container': '#eef2ff',
        'tertiary-container': '#e0f2fe',
        'on-tertiary': '#ffffff',
        'on-tertiary-fixed-variant': '#0369a1',
        error: '#ef4444',
        'on-primary-container': '#3730a3',
        'on-surface-variant': '#475569',
        secondary: '#6366f1',
        outline: '#cbd5e1',
        'surface-bright': '#ffffff',
        'on-primary-fixed': '#1e1b4b',
        'surface-container': '#f8fafc',
        'secondary-fixed': '#ede9fe',
        'secondary-container': '#f5f3ff',
        'secondary-fixed-dim': '#ddd6fe',
        'on-secondary': '#ffffff',
        primary: '#4f46e5',
        'surface-container-low': '#ffffff',
        'outline-variant': '#e2e8f0',
        'on-secondary-fixed-variant': '#5b21b6',
        surface: '#ffffff',
        'inverse-primary': '#c7d2fe',
        'surface-container-high': '#f1f5f9',
        'surface-dim': '#f8fafc',
        'inverse-on-surface': '#f8fafc',
        'on-surface': '#0f172a',
        tertiary: '#0284c7',
        'on-tertiary-container': '#0369a1',
        'on-secondary-container': '#5b21b6',
        background: '#f8fafc',
        'primary-fixed-dim': '#c7d2fe',
        'primary-fixed': '#e0e7ff',
        'surface-variant': '#f1f5f9',
        'tertiary-fixed-dim': '#bae6fd',
        'surface-container-lowest': '#ffffff',
        'on-error-container': '#7f1d1d',
        'on-error': '#ffffff',
        'on-tertiary-fixed': '#0c4a6e',
        'error-container': '#fee2e2',
        'tertiary-fixed': '#e0f2fe',
        'surface-container-highest': '#e2e8f0',
        'on-primary-fixed-variant': '#3730a3',
        'on-secondary-fixed': '#2e1065',
        'on-background': '#0f172a',
        'on-primary': '#ffffff',
        'inverse-surface': '#0f172a'
      },
      spacing: {
        margin: '2rem',
        'space-lg': '1.5rem',
        'space-xs': '0.25rem',
        'space-sm': '0.5rem',
        'space-xl': '2.5rem',
        'space-md': '1rem',
        gutter: '1.5rem'
      },
      fontFamily: {
        sans: ['"Plus Jakarta Sans"', 'Inter', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'monospace'],
        'headline-hero': ['"Plus Jakarta Sans"', 'sans-serif'],
        'headline-lg': ['"Plus Jakarta Sans"', 'sans-serif'],
        'headline-md': ['"Plus Jakarta Sans"', 'sans-serif'],
        'headline-sm': ['"Plus Jakarta Sans"', 'sans-serif'],
        'body-lg': ['Inter', '"Plus Jakarta Sans"', 'sans-serif'],
        'body-md': ['Inter', '"Plus Jakarta Sans"', 'sans-serif'],
        'body-sm': ['Inter', '"Plus Jakarta Sans"', 'sans-serif'],
        'label-lg': ['Inter', '"Plus Jakarta Sans"', 'sans-serif'],
        'label-md': ['Inter', '"Plus Jakarta Sans"', 'sans-serif'],
        'label-sm': ['Inter', '"Plus Jakarta Sans"', 'sans-serif'],
        'code-md': ['"JetBrains Mono"', 'monospace'],
      },
      fontSize: {
        'label-sm': ['11px', { lineHeight: '14px', letterSpacing: '0.04em', fontWeight: '600' }],
        'headline-hero': ['48px', { lineHeight: '56px', letterSpacing: '-0.025em', fontWeight: '700' }],
        'headline-hero-mobile': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-sm': ['12px', { lineHeight: '18px', letterSpacing: '0.005em', fontWeight: '400' }],
        'label-lg': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '600' }],
        'headline-lg': ['36px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-lg': ['16px', { lineHeight: '26px', letterSpacing: '-0.005em', fontWeight: '400' }],
        'headline-lg-mobile': ['26px', { lineHeight: '34px', letterSpacing: '-0.015em', fontWeight: '700' }],
        'headline-sm': ['18px', { lineHeight: '26px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.015em', fontWeight: '600' }],
        'code-md': ['13px', { lineHeight: '20px', letterSpacing: '0em', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '22px', letterSpacing: '0em', fontWeight: '400' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '500' }],
      },
      boxShadow: {
        'glow-cyan': '0 0 25px -4px rgba(56, 189, 248, 0.4)',
        'glow-indigo': '0 0 25px -4px rgba(99, 102, 241, 0.45)',
        'glow-violet': '0 0 30px -4px rgba(139, 92, 246, 0.45)',
        'glass-subtle': '0 8px 32px 0 rgba(0, 0, 0, 0.37)',
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "fade-in": {
          from: { opacity: "0" },
          to: { opacity: "1" },
        },
        "slide-up": {
          from: { transform: "translateY(20px)", opacity: "0" },
          to: { transform: "translateY(0)", opacity: "1" },
        },
        "scale-in": {
          from: { transform: "scale(0.95)", opacity: "0" },
          to: { transform: "scale(1)", opacity: "1" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "fade-in": "fade-in 0.3s ease-in-out",
        "slide-up": "slide-up 0.3s ease-out",
        "scale-in": "scale-in 0.2s ease-out",
      },
      backgroundImage: {
        'gradient-sidebar': 'linear-gradient(135deg, #1a1f37 0%, #1e2746 100%)',
        'gradient-card': 'linear-gradient(135deg, #1e2746 0%, #2a3659 100%)',
        'gradient-blue-purple': 'linear-gradient(135deg, #3b82f6 0%, #8b5cf6 100%)',
        'gradient-hero': 'linear-gradient(135deg, #1e3a5f 0%, #2d4a6f 100%)',
      },
    },
  },
  plugins: [],
}